package = load_json(json_path: "./package.json")

platform :android do
    desc "Android build and release to beta / release"
    lane :beta do
        gradle(task: 'clean', project_dir: './android/')
        gradle(task: 'bundle', build_type: 'Release', project_dir: './android')
        supply(package_name: 'mindsgn.studio.orbyt',json_key: "./google_play.json",  track: 'beta', aab: './android/app/build/outputs/bundle/release/app-release.aab')
        increment_version_code(gradle_file_path: "./android/app/build.gradle")
        increment_version_name(gradle_file_path: "./android/app/build.gradle", version_name: package['version'])
    end
end